In [2]:
# Numpy 1

import numpy as np

# Define array A (2 rows, 3 columns)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define array B (2 rows, 3 columns)
B = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array A:\n", A)
print("Array B:\n", B)

Array A:
 [[1 2 3]
 [4 5 6]]
Array B:
 [[10 20 30]
 [40 50 60]]


In [4]:
# Numpy 2

import numpy as np

# Define the arrays (as previously defined)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10, 20, 30],
              [40, 5, 60]])

# 1. Flatten the arrays to ensure a proper set-like intersection
# The intersect1d function works on 1D arrays.
A_flat = A.flatten()
B_flat = B.flatten()

# 2. Find the intersection (common elements)
common_elements = np.intersect1d(A_flat, B_flat)

print("Flattened Array A:", A_flat)
print("Flattened Array B:", B_flat)
print("Common Elements (Intersection):", common_elements)

Flattened Array A: [1 2 3 4 5 6]
Flattened Array B: [10 20 30 40  5 60]
Common Elements (Intersection): [5]


In [6]:
# Numpy 3

import numpy as np

# Define the array A (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define the specific range
lower_bound = 5
upper_bound = 10

# Create a boolean mask: check if elements are >= 5 AND <= 10
# The '&' operator performs the element-wise logical AND
mask = (A >= lower_bound) & (A <= upper_bound)

# Apply the mask to array A to extract the elements
extracted_numbers = A[mask]

print("Original Array A:\n", A)
print(f"Elements in the range [{lower_bound}, {upper_bound}]:", extracted_numbers)

Original Array A:
 [[1 2 3]
 [4 5 6]]
Elements in the range [5, 10]: [5 6]


In [2]:
# Numpy 4

import numpy as np
from sklearn.datasets import load_iris

# Load the Iris dataset features into the iris_2d array
# Columns: 0=Sepal Length, 1=Sepal Width, 2=Petal Length, 3=Petal Width
iris_data = load_iris()
iris_2d = iris_data.data

# Define the filtering conditions:
# Condition 1: Petal Length (3rd column, index 2) > 1.5
condition_petal_length = iris_2d[:, 2] > 1.5

# Condition 2: Sepal Length (1st column, index 0) < 5.0
condition_sepal_length = iris_2d[:, 0] < 5.0

# Combine the conditions using the element-wise logical AND operator (&)
combined_mask = condition_petal_length & condition_sepal_length

# Apply the boolean mask to the iris_2d array to filter the rows
filtered_rows = iris_2d[combined_mask]

print("--- Filtered Rows ---")
print(filtered_rows)

--- Filtered Rows ---
[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [3]:
# Pandas 1

import pandas as pd

# Load the dataset (assuming successful loading)
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

# 1. Filter rows using iloc[0::20]
filtered_rows = df.iloc[0::20]

# 2. Select the required columns
result = filtered_rows[['Manufacturer', 'Model', 'Type']]

print(result)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [5]:
# Pandas 2

import pandas as pd

# Load the dataset
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

# --- Mean Imputation (Warning-Free Method) ---

# 1. Calculate the mean of non-missing values for each column
mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

# 2. Replace missing values by REASSIGNING the result of .fillna()
# This explicitly modifies the column in the original DataFrame, avoiding the warning.
df['Min.Price'] = df['Min.Price'].fillna(mean_min_price)
df['Max.Price'] = df['Max.Price'].fillna(mean_max_price)

# --- Verification ---

print("--- Imputation Successful ---")
# The 'isnull().sum()' should confirm 0 missing values for both columns.
print("Missing values after imputation:")
print(df[['Min.Price', 'Max.Price']].isnull().sum())
print("\nFirst 5 rows (showing imputed values):")
# Example: Index 4 had a missing Min.Price (it is now the mean value).
print(df.head())

--- Imputation Successful ---
Missing values after imputation:
Min.Price    0
Max.Price    0
dtype: int64

First 5 rows (showing imputed values):
  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN    

In [6]:
# Pandas 3

import pandas as pd
import numpy as np

# Create the sample DataFrame
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# --- Filtering Logic ---

# 1. Calculate the sum of each row (axis=1). This returns a Series of row totals.
row_sums = df.sum(axis=1)

# 2. Create a Boolean mask: True for rows where the sum is greater than 100.
mask = row_sums > 100

# 3. Apply the mask to the DataFrame to get the filtered rows.
filtered_df = df[mask]

print("--- Original DataFrame (First 5 Rows) ---")
print(df.head())
print("\n--- Boolean Mask (Row Sums > 100) ---")
print(mask.head())
print("\n--- Filtered Rows (Row Sum > 100) ---")
print(filtered_df)

--- Original DataFrame (First 5 Rows) ---
    0   1   2   3
0  27  21  33  31
1  12  36  20  25
2  35  18  11  34
3  10  19  13  17
4  14  26  31  33

--- Boolean Mask (Row Sums > 100) ---
0     True
1    False
2    False
3    False
4     True
dtype: bool

--- Filtered Rows (Row Sum > 100) ---
     0   1   2   3
0   27  21  33  31
4   14  26  31  33
5   20  39  33  32
9   23  39  16  25
11  38  35  14  34
13  35  10  34  24
14  13  39  37  27
